[test]

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -9,7 +9,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        platform: [ ubuntu-24.04, macos-15 ]
+        platform: [ ubuntu-24.04, macos-15, windows-latest ]
     name: Build reindexer for ${{ matrix.platform }}
     runs-on: ${{ matrix.platform }}
     defaults:
@@ -21,7 +21,8 @@ jobs:
         run: |
           sudo apt-get update -y
           sudo apt-get install -y build-essential cmake
-      - name: Build reindexer
+      - name: Build reindexer (Unix)
+        if: startsWith(matrix.platform, 'ubuntu') || startsWith(matrix.platform, 'macos')
         run: |
           git clone https://github.com/Restream/reindexer.git
           cd reindexer
@@ -43,88 +44,101 @@ jobs:
             cpp_src/leveldb_lib* cpp_src/snappy_lib* \
             cpp_src/cmd/reindexer_tool/replxx_lib* Testing cpp_src/gtests/tests/logs
           find . -empty -type d -delete
-      - name: Store build artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: build_${{ matrix.platform }}
-          path: reindexer/build
-
-  test:
-    needs: build_reindexer
-    strategy:
-      fail-fast: false
-      matrix:
-        python: [ "3.9", "3.13" ]
-        platform: [ ubuntu-24.04, macos-15 ]
-        include:
-          - python: "3.8"
-            platform: ubuntu-24.04
-            distutils: stdlib
-          - python: "3.10"
-            platform: ubuntu-24.04
-          - python: "3.11"
-            platform: ubuntu-24.04
-          - python: "3.12"
-            platform: ubuntu-24.04
-    runs-on: ${{ matrix.platform }}
-    env:
-      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils || 'local' }}
-      MACOSX_DEPLOYMENT_TARGET: "15"
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout PyReindexer repo
-        uses: actions/checkout@v4
-
-      - name: Download build artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: build_${{ matrix.platform }}
-          path: reindexer_build
-      - name: Install Reindexer (MacOS)
-        if: startsWith(matrix.platform, 'macos')
+      - name: Build reindexer (Windows)
+        if: startsWith(matrix.platform, 'windows')
+        shell: pwsh
         run: |
-          brew update
+          conda install openblas -y
+          cd C:\temp\reindexer
           git clone https://github.com/Restream/reindexer.git
-          cd reindexer
-          ./dependencies.sh
-          cd ../reindexer_build
-          tar -xzf reindexer-*-Darwin-server.tar.gz
-          tar -xzf reindexer-*-Darwin-dev.tar.gz
-          sudo cp -rf usr/local/* /usr/local/
-      - name: Install Reindexer (Ubuntu)
-        if: startsWith(matrix.platform, 'ubuntu')
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y libunwind-dev
-          cd reindexer_build
-          sudo dpkg -i reindexer-server*.deb || true
-          sudo apt-get install -y -f || true
-          sudo dpkg -i reindexer-dev*.deb || true
-          sudo apt-get install -y -f || true
+          mkdir build && cd build
+          cmake -G "Visual Studio 18 2026" .. -Ax64
+          cmake --build . --config Release /p:MultiProcessorCompilation=true --parallel 4
+          cmake --install . --config Release --prefix C:\reindexer-install
+          cpack
+          cd ..\..
+#      - name: Store build artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: build_${{ matrix.platform }}
+#          path: reindexer/build
 
-      - name: Set up Python ${{ matrix.python }}
-        id: python-install
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python }}
-          allow-prereleases: false
-        env:
-          PIP_DISABLE_PIP_VERSION_CHECK: 1
-          # Workaround for actions/setup-python#981 (env var only modified for this specific step)
-          SETUPTOOLS_USE_DISTUTILS: >-
-            ${{ matrix.platform == 'macos-15' && matrix.python == '3.9' && 'stdlib' || 'local' }}-
-            ${{ matrix.platform == 'macos-latest' && matrix.python == '3.9' && 'stdlib' || 'local' }}-
-      - name: Install Python dependencies
-        run: |
-          python -m pip install --upgrade --disable-pip-version-check pip setuptools build
-          python -m pip install -r requirements.txt
-      - name: Build PyReindexer
-        run: |
-          python -m build
-          python -m pip install .
-      - name: Test
-        run: |
-          cd pyreindexer
-          $GITHUB_WORKSPACE/.github/workflows/test.sh
+#  test:
+#    needs: build_reindexer
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        python: [ "3.9", "3.13" ]
+#        platform: [ ubuntu-24.04, macos-15, windows-latest ]
+#        include:
+#          - python: "3.8"
+#            platform: ubuntu-24.04
+#            distutils: stdlib
+#          - python: "3.10"
+#            platform: ubuntu-24.04
+#          - python: "3.11"
+#            platform: ubuntu-24.04
+#          - python: "3.12"
+#            platform: ubuntu-24.04
+#    runs-on: ${{ matrix.platform }}
+#    env:
+#      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils || 'local' }}
+#      MACOSX_DEPLOYMENT_TARGET: "15"
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - name: Checkout PyReindexer repo
+#        uses: actions/checkout@v4
+#
+#      - name: Download build artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: build_${{ matrix.platform }}
+#          path: reindexer_build
+#      - name: Install Reindexer (MacOS)
+#        if: startsWith(matrix.platform, 'macos')
+#        run: |
+#          brew update
+#          git clone https://github.com/Restream/reindexer.git
+#          cd reindexer
+#          ./dependencies.sh
+#          cd ../reindexer_build
+#          tar -xzf reindexer-*-Darwin-server.tar.gz
+#          tar -xzf reindexer-*-Darwin-dev.tar.gz
+#          sudo cp -rf usr/local/* /usr/local/
+#      - name: Install Reindexer (Ubuntu)
+#        if: startsWith(matrix.platform, 'ubuntu')
+#        run: |
+#          sudo apt-get update -y
+#          sudo apt-get install -y libunwind-dev
+#          cd reindexer_build
+#          sudo dpkg -i reindexer-server*.deb || true
+#          sudo apt-get install -y -f || true
+#          sudo dpkg -i reindexer-dev*.deb || true
+#          sudo apt-get install -y -f || true
+#
+#      - name: Set up Python ${{ matrix.python }}
+#        id: python-install
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: ${{ matrix.python }}
+#          allow-prereleases: false
+#        env:
+#          PIP_DISABLE_PIP_VERSION_CHECK: 1
+#          # Workaround for actions/setup-python#981 (env var only modified for this specific step)
+#          SETUPTOOLS_USE_DISTUTILS: >-
+#            ${{ matrix.platform == 'macos-15' && matrix.python == '3.9' && 'stdlib' || 'local' }}-
+#            ${{ matrix.platform == 'macos-latest' && matrix.python == '3.9' && 'stdlib' || 'local' }}-
+#      - name: Install Python dependencies
+#        run: |
+#          python -m pip install --upgrade --disable-pip-version-check pip setuptools build
+#          python -m pip install -r requirements.txt
+#      - name: Build PyReindexer
+#        run: |
+#          python -m build
+#          python -m pip install .
+#      - name: Test
+#        run: |
+#          cd pyreindexer
+#          $GITHUB_WORKSPACE/.github/workflows/test.sh
