[test] musllinux deploy parallel

diff --git a/.github/workflows/test-deploy-workflow.yml b/.github/workflows/test-deploy-workflow.yml
--- a/.github/workflows/test-deploy-workflow.yml
+++ b/.github/workflows/test-deploy-workflow.yml
@@ -1,18 +1,26 @@
 name: Upload Release package to TestPyPI
 on:
-  pull_request:
-    types: [ opened, reopened ]
-    paths-ignore:
-      - 'pyreindexer/tests/**'
+  push:
+    branches-ignore:
+      - master
 
 jobs:
   build_wheels:
-    name: Build wheels on ${{ matrix.platform }}
+    name: Build wheels (${{ matrix.name }})
     runs-on: ${{ matrix.platform }}
     strategy:
       fail-fast: false
       matrix:
-        platform: [ ubuntu-24.04, macos-15 ]
+        include:
+          - platform: ubuntu-24.04
+            cibw_platform: manylinux
+            name: manylinux-x86_64
+          - platform: ubuntu-24.04
+            cibw_platform: musllinux
+            name: musllinux-x86_64
+          - platform: macos-15
+            name: macos-arm64
+            cibw_platform: ""
     env:
       DEPLOY_BUILD_PYTHON_VERSION: "3.8"
       MACOSX_DEPLOYMENT_TARGET: "15"
@@ -29,224 +37,229 @@ jobs:
       - name: Install Python dependencies
         run: python -m pip install --upgrade pip cibuildwheel
       - name: Build PyReindexer wheels
-        run: python -m cibuildwheel --output-dir dist
-      - name: Store all build artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: pyrx_artifacts_wheels_${{ matrix.platform }}
-          path: dist/*
-
-  build_sdist:
-    name: Build sdist on Ubuntu
-    runs-on: ubuntu-24.04
-    env:
-      DEPLOY_BUILD_PYTHON_VERSION: "3.12"
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout PyReindexer repo
-        uses: actions/checkout@v4
-      - name: Set up Python ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
-      - name: Install Python dependencies
-        run: python -m pip install --upgrade pip build
-      - name: Build PyReindexer dist
-        run: python -m build --sdist
-      - name: Store all build artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: pyrx_artifacts_sdist
-          path: dist/*
-
-  deploy:
-    name: Upload to TestPyPI (ubuntu)
-    runs-on: ubuntu-24.04
-    needs: [ build_wheels, build_sdist ]
-    environment:
-      name: testpypi
-      url: https://test.pypi.org/p/pyreindexer/
-    steps:
-      - name: Download pyreindexer artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: pyrx_artifacts*
-          path: dist
-          merge-multiple: true
-      - name: Publish package distributions to TestPyPI
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          verbose: true
-          # user: __token__ ## used as default
-          password: pypi-${{ secrets.TESTPYPI_TOKEN }}
-          repository-url: https://test.pypi.org/legacy/
-          attestations: false
-
-  build_reindexer:
-    strategy:
-      fail-fast: false
-      matrix:
-        platform: [ ubuntu-24.04, macos-15 ]
-    name: Build reindexer for ${{ matrix.platform }}
-    runs-on: ${{ matrix.platform }}
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Install build dependencies (Ubuntu)
-        if: startsWith(matrix.platform, 'ubuntu')
         run: |
-          sudo apt-get update -y
-          sudo apt-get install -y build-essential cmake
-      - name: Build reindexer
-        run: |
-          git clone https://github.com/Restream/reindexer.git
-          cd reindexer
-          if [[ "${{ matrix.platform }}" == ubuntu-* ]]; then
-            sudo ./dependencies.sh
+          if [ -n "${{ matrix.cibw_platform }}" ]; then
+            python -m cibuildwheel --output-dir dist --platform ${{ matrix.cibw_platform }}
           else
-            ./dependencies.sh
+            python -m cibuildwheel --output-dir dist
           fi
-          mkdir -p build && cd build
-          cmake ..
-          make -j4
-          cpack
-          find . -name CMakeFiles -o -name "*.cc" -o -name "*.h" -o \
-            -name Makefile -o -name _cmrc -o -name "*.json" -o -name "*.txt" -o -name \
-            "*.in" | xargs -n1 rm -rf
-          rm -rf _CPack_Packages \
-            cpp_src/server/reindexer_server_resources cpp_src/server/face \
-            cpp_src/server/swagger cpp_src/cmd/reindexer_server/contrib \
-            cpp_src/leveldb_lib* cpp_src/snappy_lib* \
-            cpp_src/cmd/reindexer_tool/replxx_lib* Testing cpp_src/gtests/tests/logs
-          find . -empty -type d -delete
-      - name: Store build artifacts
+      - name: Store all build artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: build_${{ matrix.platform }}
-          path: reindexer/build
+          name: pyrx_artifacts_wheels_${{ matrix.name }}
+          path: dist/*
 
-  test_dist:
-    needs: [ build_reindexer, deploy ]
-    strategy:
-      fail-fast: false
-      matrix:
-        platform: [ ubuntu-24.04, macos-15 ]
-        python: [ "3.13" ]
-    runs-on: ${{ matrix.platform }}
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout PyReindexer
-        uses: actions/checkout@v4
-
-      - name: Download build artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: build_${{ matrix.platform }}
-          path: reindexer_build
-      - name: Install Reindexer (MacOS)
-        if: startsWith(matrix.platform, 'macos')
-        run: |
-          brew update
-          git clone https://github.com/Restream/reindexer.git
-          cd reindexer
-          ./dependencies.sh
-          cd ../reindexer_build
-          tar -xzf reindexer-*-Darwin-server.tar.gz
-          tar -xzf reindexer-*-Darwin-dev.tar.gz
-          sudo cp -rf usr/local/* /usr/local/
-      - name: Install Reindexer (Ubuntu)
-        if: startsWith(matrix.platform, 'ubuntu')
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y libunwind-dev
-          cd reindexer_build
-          sudo dpkg -i reindexer-server*.deb || true
-          sudo apt-get install -y -f || true
-          sudo dpkg -i reindexer-dev*.deb || true
-          sudo apt-get install -y -f || true
-
-      - name: Set up Python ${{ matrix.python }}
-        uses: actions/setup-python@v5
-        env:
-          PIP_DISABLE_PIP_VERSION_CHECK: 1
-        with:
-          python-version: ${{ matrix.python }}
-      - name: Install PyReindexer
-        run: |
-          python -m pip install --upgrade --disable-pip-version-check pip importlib_metadata setuptools wheel
-          # needs `no-binary` for the forced sdist install
-          python -m pip install -vvv --no-deps --no-build-isolation --no-binary pyreindexer --index-url https://test.pypi.org/simple/ pyreindexer
-      - name: Prepare Test Environment
-        run: python -m pip install -r requirements.txt
-      - name: Test
-        run: |
-          cd pyreindexer
-          $GITHUB_WORKSPACE/.github/workflows/test.sh
-
-  test_wheel:
-    needs: [ build_reindexer, deploy ]
-    strategy:
-      fail-fast: false
-      matrix:
-        platform: [ ubuntu-24.04, macos-15 ]
-        python: [ "3.8", "3.13" ]
-        rxmode: [ builtin, cproto ]
-    runs-on: ${{ matrix.platform }}
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout PyReindexer
-        uses: actions/checkout@v4
-
-      - name: Download build artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: build_${{ matrix.platform }}
-          path: reindexer_build
-      - name: Install Reindexer (MacOS)
-        if: startsWith(matrix.platform, 'macos') && matrix.rxmode == 'cproto'
-        run: |
-          brew update
-          git clone https://github.com/Restream/reindexer.git
-          cd reindexer
-          ./dependencies.sh
-          cd ../reindexer_build
-          tar -xzf reindexer-*-Darwin-server.tar.gz
-          tar -xzf reindexer-*-Darwin-dev.tar.gz
-          sudo cp -rf usr/local/* /usr/local/
-      - name: Install Reindexer (Ubuntu)
-        if: startsWith(matrix.platform, 'ubuntu') && matrix.rxmode == 'cproto'
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y libunwind-dev
-          cd reindexer_build
-          sudo dpkg -i reindexer-server*.deb || true
-          sudo apt-get install -y -f || true
-          sudo dpkg -i reindexer-dev*.deb || true
-          sudo apt-get install -y -f || true
-      - name: Install Openblas (Ubuntu)
-        if: startsWith(matrix.platform, 'ubuntu') && matrix.rxmode == 'builtin'
-        run: sudo apt-get install -y libopenblas-pthread-dev
-
-      - name: Set up Python ${{ matrix.python }}
-        uses: actions/setup-python@v5
-        env:
-          PIP_DISABLE_PIP_VERSION_CHECK: 1
-        with:
-          python-version: ${{ matrix.python }}
-      - name: Install PyReindexer
-        run: |
-          python -m pip install --upgrade --disable-pip-version-check pip importlib_metadata
-          python -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps pyreindexer
-      - name: Prepare Test Environment
-        run: python -m pip install -r requirements.txt
-      - name: Test ${{ matrix.rxmode }}
-        run: |
-          cd pyreindexer
-          $GITHUB_WORKSPACE/.github/workflows/test.sh ${{matrix.rxmode}}
+#  build_sdist:
+#    name: Build sdist on Ubuntu
+#    runs-on: ubuntu-24.04
+#    env:
+#      DEPLOY_BUILD_PYTHON_VERSION: "3.12"
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - name: Checkout PyReindexer repo
+#        uses: actions/checkout@v4
+#      - name: Set up Python ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
+#      - name: Install Python dependencies
+#        run: python -m pip install --upgrade pip build
+#      - name: Build PyReindexer dist
+#        run: python -m build --sdist
+#      - name: Store all build artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: pyrx_artifacts_sdist
+#          path: dist/*
+#
+#  deploy:
+#    name: Upload to TestPyPI (ubuntu)
+#    runs-on: ubuntu-24.04
+#    needs: [ build_wheels, build_sdist ]
+#    environment:
+#      name: testpypi
+#      url: https://test.pypi.org/p/pyreindexer/
+#    steps:
+#      - name: Download pyreindexer artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          pattern: pyrx_artifacts*
+#          path: dist
+#          merge-multiple: true
+#      - name: Publish package distributions to TestPyPI
+#        uses: pypa/gh-action-pypi-publish@release/v1
+#        with:
+#          verbose: true
+#          # user: __token__ ## used as default
+#          password: pypi-${{ secrets.TESTPYPI_TOKEN }}
+#          repository-url: https://test.pypi.org/legacy/
+#          attestations: false
+#
+#  build_reindexer:
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        platform: [ ubuntu-24.04, macos-15 ]
+#    name: Build reindexer for ${{ matrix.platform }}
+#    runs-on: ${{ matrix.platform }}
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - name: Install build dependencies (Ubuntu)
+#        if: startsWith(matrix.platform, 'ubuntu')
+#        run: |
+#          sudo apt-get update -y
+#          sudo apt-get install -y build-essential cmake
+#      - name: Build reindexer
+#        run: |
+#          git clone https://github.com/Restream/reindexer.git
+#          cd reindexer
+#          if [[ "${{ matrix.platform }}" == ubuntu-* ]]; then
+#            sudo ./dependencies.sh
+#          else
+#            ./dependencies.sh
+#          fi
+#          mkdir -p build && cd build
+#          cmake ..
+#          make -j4
+#          cpack
+#          find . -name CMakeFiles -o -name "*.cc" -o -name "*.h" -o \
+#            -name Makefile -o -name _cmrc -o -name "*.json" -o -name "*.txt" -o -name \
+#            "*.in" | xargs -n1 rm -rf
+#          rm -rf _CPack_Packages \
+#            cpp_src/server/reindexer_server_resources cpp_src/server/face \
+#            cpp_src/server/swagger cpp_src/cmd/reindexer_server/contrib \
+#            cpp_src/leveldb_lib* cpp_src/snappy_lib* \
+#            cpp_src/cmd/reindexer_tool/replxx_lib* Testing cpp_src/gtests/tests/logs
+#          find . -empty -type d -delete
+#      - name: Store build artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: build_${{ matrix.platform }}
+#          path: reindexer/build
+#
+#  test_dist:
+#    needs: [ build_reindexer, deploy ]
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        platform: [ ubuntu-24.04, macos-15 ]
+#        python: [ "3.13" ]
+#    runs-on: ${{ matrix.platform }}
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - name: Checkout PyReindexer
+#        uses: actions/checkout@v4
+#
+#      - name: Download build artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: build_${{ matrix.platform }}
+#          path: reindexer_build
+#      - name: Install Reindexer (MacOS)
+#        if: startsWith(matrix.platform, 'macos')
+#        run: |
+#          brew update
+#          git clone https://github.com/Restream/reindexer.git
+#          cd reindexer
+#          ./dependencies.sh
+#          cd ../reindexer_build
+#          tar -xzf reindexer-*-Darwin-server.tar.gz
+#          tar -xzf reindexer-*-Darwin-dev.tar.gz
+#          sudo cp -rf usr/local/* /usr/local/
+#      - name: Install Reindexer (Ubuntu)
+#        if: startsWith(matrix.platform, 'ubuntu')
+#        run: |
+#          sudo apt-get update -y
+#          sudo apt-get install -y libunwind-dev
+#          cd reindexer_build
+#          sudo dpkg -i reindexer-server*.deb || true
+#          sudo apt-get install -y -f || true
+#          sudo dpkg -i reindexer-dev*.deb || true
+#          sudo apt-get install -y -f || true
+#
+#      - name: Set up Python ${{ matrix.python }}
+#        uses: actions/setup-python@v5
+#        env:
+#          PIP_DISABLE_PIP_VERSION_CHECK: 1
+#        with:
+#          python-version: ${{ matrix.python }}
+#      - name: Install PyReindexer
+#        run: |
+#          python -m pip install --upgrade --disable-pip-version-check pip importlib_metadata setuptools wheel
+#          # needs `no-binary` for the forced sdist install
+#          python -m pip install -vvv --no-deps --no-build-isolation --no-binary pyreindexer --index-url https://test.pypi.org/simple/ pyreindexer
+#      - name: Prepare Test Environment
+#        run: python -m pip install -r requirements.txt
+#      - name: Test
+#        run: |
+#          cd pyreindexer
+#          $GITHUB_WORKSPACE/.github/workflows/test.sh
+#
+#  test_wheel:
+#    needs: [ build_reindexer, deploy ]
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        platform: [ ubuntu-24.04, macos-15 ]
+#        python: [ "3.8", "3.13" ]
+#        rxmode: [ builtin, cproto ]
+#    runs-on: ${{ matrix.platform }}
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - name: Checkout PyReindexer
+#        uses: actions/checkout@v4
+#
+#      - name: Download build artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: build_${{ matrix.platform }}
+#          path: reindexer_build
+#      - name: Install Reindexer (MacOS)
+#        if: startsWith(matrix.platform, 'macos') && matrix.rxmode == 'cproto'
+#        run: |
+#          brew update
+#          git clone https://github.com/Restream/reindexer.git
+#          cd reindexer
+#          ./dependencies.sh
+#          cd ../reindexer_build
+#          tar -xzf reindexer-*-Darwin-server.tar.gz
+#          tar -xzf reindexer-*-Darwin-dev.tar.gz
+#          sudo cp -rf usr/local/* /usr/local/
+#      - name: Install Reindexer (Ubuntu)
+#        if: startsWith(matrix.platform, 'ubuntu') && matrix.rxmode == 'cproto'
+#        run: |
+#          sudo apt-get update -y
+#          sudo apt-get install -y libunwind-dev
+#          cd reindexer_build
+#          sudo dpkg -i reindexer-server*.deb || true
+#          sudo apt-get install -y -f || true
+#          sudo dpkg -i reindexer-dev*.deb || true
+#          sudo apt-get install -y -f || true
+#      - name: Install Openblas (Ubuntu)
+#        if: startsWith(matrix.platform, 'ubuntu') && matrix.rxmode == 'builtin'
+#        run: sudo apt-get install -y libopenblas-pthread-dev
+#
+#      - name: Set up Python ${{ matrix.python }}
+#        uses: actions/setup-python@v5
+#        env:
+#          PIP_DISABLE_PIP_VERSION_CHECK: 1
+#        with:
+#          python-version: ${{ matrix.python }}
+#      - name: Install PyReindexer
+#        run: |
+#          python -m pip install --upgrade --disable-pip-version-check pip importlib_metadata
+#          python -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps pyreindexer
+#      - name: Prepare Test Environment
+#        run: python -m pip install -r requirements.txt
+#      - name: Test ${{ matrix.rxmode }}
+#        run: |
+#          cd pyreindexer
+#          $GITHUB_WORKSPACE/.github/workflows/test.sh ${{matrix.rxmode}}
